ads/urls.py
from os import name
from django.urls import path, reverse_lazy
from .import views

app_name ='ads'

urlpatterns = [
    path('', views.adshomeview, name='adshomeview'),
    path('all/', views.AdListView.as_view(), name='all'),
    path('ad_create/', views.ad_create, name='ad_create'),
    path('<int:id>/ad_delete', views.ad_delete, name='ad_delete'),
    path('<int:id>/ad_edit', views.ad_edit, name='ad_edit'),
]

autos/urls.py
from django.urls import path

from .import views

app_name = 'auto'

urlpatterns = [ 
    path('', views.autohomeview, name='autohomeview'),
    path('listautos', views.autolist, name='autolist'),
    path('addauto/', views.addauto, name='addauto'),
    path('<int:id>/editauto', views.autoedit, name='autoedit'),
    path('<int:id>/deleteauto', views.autodelete, name='autodelete'),

    path('listmakes/', views.makeslist, name='makeslist'),
    path('addmake/', views.addmake, name='addmake'),
    path('<int:id>/editmake', views.editmake, name='editmake'),
    path('<int:id>/deletemake', views.makedelete, name='makedelete'),


]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    #path('', include('home.urls')),  # Change to ads.urls
    path('', include('ads.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

autos/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Make(models.Model):
    name_text = models.CharField(max_length=100)

    def __str__(self):
        return self.name_text


class Autos(models.Model):
    nickname = models.CharField(max_length=100)
    make = models.ForeignKey(Make, on_delete=CASCADE)
    milage = models.IntegerField(default=0)
    comments = models.CharField(max_length=1000)


    

autos/views.py
import re
from django.http import response
from django.shortcuts import get_object_or_404, redirect, render


from .models import Autos
from .models import Make

# Create your views here.


def autohomeview(request):
    return render(request, 'autos/auto_home.html')


def addauto(request):

    if request.method == 'POST':
        obj = Autos()
        obj.nickname = request.POST['nickname']

        make = Make.objects.get(pk = request.POST.get('make'))
        obj.make = make

        obj.milage = request.POST['milage']
        obj.comments = request.POST['comments']
        obj.save()

        return redirect('/autos/listautos')

    else:
        make = Make.objects.all()
        context = {
            'make': make
        }
        return render(request, 'autos/add_auto.html', context)


def autolist(request):

    autolist = Autos.objects.all()

    context = {
        'autolist': autolist
    }
    return render(request, 'autos/auto_list.html', context)


def autoedit(request, id):

    auto_details = get_object_or_404(Autos, pk=id)
    make = Make.objects.all()

    context = {
        'autodetails': auto_details,
        'make' : make,
        'selected_make' : auto_details.make
    }

    if request.method == 'POST' and 'buttonsubmit' in request.POST:

        obj = get_object_or_404(Autos, pk=id)

        obj.nickname = request.POST['nickname']
        obj.make = get_object_or_404(Make, pk=request.POST['make'])
        obj.milage = request.POST['milage']
        obj.comments = request.POST['comments']
        obj.save()

        return redirect('/autos/listautos')

    elif request.method == 'POST' and 'buttondelete' in request.POST:
        return redirect(str(id) + '/deleteauto')

    else:
        return render(request, 'autos/edit_auto.html', context)


def autodelete(request, id):
    Autos.objects.filter(id=id).delete()
    return redirect('/autos/listautos')




def addmake(request):

    if request.method == 'POST':
        obj = Make()
        obj.name_text = request.POST['make']

        obj.save()
        return redirect ('/autos/listmakes')
        #return redirect('auto:makeslist')
    else:
        return render(request, 'autos/add_make.html', {})


def makeslist(request):
    makelist = Make.objects.all()

    context = {
        'makelist': makelist
    }

    return render (request, 'autos/make_list.html',context)


def editmake(request, id):
    make = Make.objects.get(pk=id)
    contex = {
        'make':make
    }

    if request.method == 'POST' and 'buttonupdate' in request.POST:
        obj = get_object_or_404(Make, pk=id)
        obj.name_text = request.POST['make']
        obj.save()

        return redirect('auto:makeslist')

    elif request.method == 'POST' and 'buttondelete' in request.POST:
        return redirect(str(id) + '/deletemake')
    else:
        return render(request, 'autos/edit_make.html', contex)
        



def makedelete(request, id):
    Make.objects.filter(id=id).delete()
    return redirect('auto:makeslist')

autos/templates/autos/add_auto.html
<form action="{% url 'auto:addauto' %}" method="post">
    {% csrf_token %}
    <p>
        <label for="nickname">Nickname : </label>
        <input type="text" name="nickname" id="nickname" value="{{ autodetails.nickname }}">
    </p>
    <p>
        <label for="make">Make : </label>
        <select name="make" id="make">
            {% for item in make %}
            <option value="{{ item.id }} ">{{ item }}</option>
            {% endfor %}
        </select>
    </p>
    <p>
        <label for="milage">Milage : </label>
        <input type="text" name="milage" id="milage" value="{{ autodetails.milage }}">
    </p>
    <p>
        <label for="comments">Comments : </label>
        <input type="textarea" name="comments" id="comments" value="{{ autodetails.comments }}">
    </p>


    <input type="submit" name = "buttonsubmit" value="Add">
</form>

autos/templates/autos/add_make.html
<form action="{% url 'auto:addmake' %}" method="post">
    {% csrf_token %}
    <p>
        <label for = "make"> Make : </label>
        <input type="text" name="make" id="make">
    </p>
    <input type="submit" name="buttonsubmit" value="Add">
</form>

autos/templates/autos/auto_home.html
<ul>
    <li>
        <p><a href="./listmakes">Manage makes</a></p>
    </li>
    <li>
        <p><a href="./listautos">Manage autos</a></p>
    </li>
</ul>

autos/templates/autos/auto_list.html
<a href="./addauto">Add New Auto </a> <br>

<h2>Auto list </h2>


<ul>
    {% for auto in autolist %}
    <li>

        <a href="{% url 'auto:autoedit' auto.id %}" />
        {{ forloop.counter }} :
        {{ auto.nickname }} - {{ auto.make }} - {{ auto.milage }} - {{ auto.comments }}
    </li>

    {% endfor %}
</ul>

autos/templates/autos/edit_auto.html
{{ autodetails }}

<form action="{% url 'auto:autoedit' autodetails.id %} " method="post">
    {% csrf_token %}
    <p>
        <label for="nickname">Nickname : </label>
        <input type="text" name="nickname" id="nickname" value="{{ autodetails.nickname }}">
    </p>
    <p>
        <label for="make">Make : </label>

        <select name="make" id="make">
            {% for item in make %}
            <option value="{{ item.id}} " {% if item.id == selected_make.id %} selected {% endif %}>
                {{ item.name_text }}
            </option>


            {% endfor %}
        </select>

    </p>
    <p>
        <label for="milage">Milage : </label>
        <input type="text" name="milage" id="milage" value="{{ autodetails.milage }}">
    </p>
    <p>
        <label for="comments">Comments : </label>
        <input type="textarea" name="comments" id="comments" value="{{ autodetails.comments }}">
    </p>


    <input type="submit" name="buttonsubmit" value="Update">
    <input type="submit" name="buttondelete" formaction="{% url 'auto:autodelete' autodetails.id %}" value="Delete">
</form>

autos/templates/autos/edit_make.html
<form action="{% url 'auto:editmake' make.id %}" method="post">
    {% csrf_token %}
    <p>
        <label for="make">Make : </label>
        <input type="text" name="make" id="make" value="{{ make.name_text }}">
    </p>

    <input type="submit" name="buttonupdate" value="Update">
    <input type="submit" name="buttondelete" formaction="{% url 'auto:makedelete' make.id %}" value="Delete">


</form>

autos/templates/autos/make_list.html
<!-- <a href="/addmake">Add New Make </a> -->
<a href="{% url 'auto:addmake' %}">Add New Make</a>

<h2>Make list </h2>


<ul>
    {% for make in makelist %}
    <li>
     
        <a href="{% url 'auto:editmake' make.id %}"/>
        {{ forloop.counter }} : 
        {{  make.name_text }}
    </li>

    {% endfor %}
</ul>