ads/urls.py
from os import name
from django.urls import path, reverse_lazy
from .import views

app_name ='ads'

urlpatterns = [
    path('', views.adshomeview, name='adshomeview'),
    path('all/', views.AdListView.as_view(), name='all'),
    path('ad_create/', views.ad_create, name='ad_create'),
    path('<int:id>/ad_delete', views.ad_delete, name='ad_delete'),
    path('<int:id>/ad_edit', views.ad_edit, name='ad_edit'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    #path('', include('home.urls')),  # Change to ads.urls
    path('', include('ads.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

ads/models.py
from django.core import validators
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


# Create your models here.

class Ad(models.Model):
    title = models.CharField(
            max_length=200,
            validators =[MinLengthValidator(2, "Title must be grater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    # show up in the admin list 

    def __str__(self):
        return self.title
    

ads/forms.py
from django import forms
from django.db.models import fields
from .models import Ad

class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        #exclude = ["owner"]
        fields = ('title', 'price', 'text', 'owner')

ads/views.py
import django
from django.contrib.messages.api import error
from django.http import HttpResponse, request
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from ads import models
from ads.forms import AdForm
from django.contrib import messages
from django.contrib.auth.models import User





from ads.models import Ad

# Create your views here.

def adshomeview(request):
    ads= models.Ad.objects.order_by('id')
    context = {
          'ads':ads,
      }

    return render(request, 'ads/ads_home.html', context)


class AdListView(ListView):
    ad = Ad
    template_name = 'ads/ad_list.html'
    
    def get(self, request, *args, **kwargs):
        
    
      ads = models.Ad.objects.filter(owner = request.user.id)
      
      context = {
          'ads':ads,
      }
      return render(request, self.template_name, context)




def ad_create(request):

    template ="ads/ad_create.html"

    if request.method == 'POST':
        ad_form = AdForm(request.POST, request.FILES)

        if ad_form.is_valid():
            ad_form.save()
            messages.success(request, ("Your Ad was created sucessfully"))
        else:
            messages.error(request, "Error saving form")
        
        return redirect("ads:adshomeview")
    
    ad_form = AdForm()
    ads = Ad.objects.all()
    context={
        'ad_form':ad_form,
        'ads':ads,
        }
    return render(request, template, context )
        

def ad_delete(request, id):
    Ad.objects.filter(id=id).delete()

    return redirect("ads:adshomeview")

def ad_edit(request, id):
    addetail = Ad.objects.get(id=id)

    users = User.objects.all()
    
   
    context = {
        'addetails':addetail,
        'owners': users,
    }

    if request.method == 'POST' and 'buttonsubmit' in request.POST: 
        obj = get_object_or_404(Ad, pk=id)
        
        obj.title = request.POST.get('title')
        obj.price = request.POST.get('price')
        obj.text = request.POST.get('text')
       
    
        owner = User.objects.get(username = request.POST.get('owner'))


        obj.owner = owner
        obj.save()

        return redirect('/all')
    else:
        return render (request, 'ads/ad_edit.html', context)
    

ads/templates/ads/ad_create.html
{% extends "base_menu.html" %}

{% block content %}

<h2>Ads Create </h2>
{% load crispy_forms_tags %}  

<form method="POST">
    {% csrf_token %}
    {{ ad_form |crispy}}
    <button class=" btn btn-primary my-4" type="submit">Submit</button>
</form>


{% endblock %}

ads/templates/ads/ad_edit.html
{% extends "base_menu.html" %}

{% block content %}

<h2>Edit Ads</h2>
<!-- {% load crispy_forms_tags %}  -->

<form action= "{% url 'ads:ad_edit' addetails.id %}" method="POST">
    {% csrf_token %}
    <div class="form-group row">
        <!-- {{ ad_form |crispy}} -->
        <label for="title" class="col-sm-2 col-form-label"> Title : </label>
        <input type="text" class="form-control-plaintext" name="title" value="{{ addetails.title }}">
    </div>
    <p>
        <label for="price" class="col-sm-2 col-form-label"> Price : </label>
        <input type="text" class="form-control-plaintext" name="price" value="{{ addetails.price }}">
    </p>
    <p>
        <label for="text" class="col-sm-2 col-form-label"> Text : </label>
        <input type="textarea" class="form-control-plaintext" name="text" value="{{ addetails.text }}">
    </p>
    <p>
        <label for="owner" class="col-sm-2 col-form-label" > Owner : </label>
       <select name="owner" class="custom-select mr-sm-2" id="owner">
           {% for owner in owners %}
           <option value="{{ owner.username }} " {% if owner.id == addetails.owner %} selected {% endif %}>
               {{ owner.username }}
           </option>
           {% endfor %}
       </select>
    </p>
    <p>
        <label for="created_at"> Created At : </label>
        {{ addetails.created_at }}
    </p>
    <p>
        <label for="updated_at"> updated At : </label>
        {{ addetails.updated_at }}
    </p>

    <button class=" btn btn-primary my-4" name="buttonsubmit" type="submit">Submit</button>
</form>

{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}
<h1>Ads List</h1>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th> Title </th>
            <th> Price </th>
            <th> Text </th>
            <th> Owner </th>
            <th> Created At </th>
            <th> Updated At </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for item in ads %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.text }}</td>
            <td>{{ item.owner }}</td>
            <td>{{ item.created_at }}</td>
            <td>{{ item.updated_at }}</td>
            <td>
                <button type="button" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </button>
            </td>
            <td>
                <button type="button" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span> Del
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

ads/templates/ads/ads_home.html
{% extends "base_menu.html" %}

{% block content %}

<h1>Adds home </h1>
<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th> Title </th>
            <th> Price </th>
            <th> Text </th>
            <th> Owner </th>
            <th> Created At </th>
            <th> Updated At </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for item in ads %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.price }}</td>
            <td>{{ item.text }}</td>
            <td>{{ item.owner }}</td>
            <td>{{ item.created_at }}</td>
            <td>{{ item.updated_at }}</td>
            <td>
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" name="buttonedit" formaction="{% url 'ads:ad_edit' item.id %}"
                        class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span> Edit
                    </button>
                </form>
            </td>
            <td>
                <form method="post" onsubmit="window.confirmdelete()">
                    {% csrf_token %}
                    <button type="submit" name="buttondelete" formaction="{% url 'ads:ad_delete' item.id %}"
                        class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span> Del
                    </button>
                </form>
                <script type="text/javascript">window.confirmdelete = function() { var isValid = confirm('Are you sure ?');if (!isValid) { event.preventDefault();  alert("It wont delete. Yay!");}}</script>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

ads/templates/ads/article_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Article</h1>

<p>Are you sure you want to delete the article: {{ article }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

ads/templates/ads/article_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ article.updated_at|naturaltime }})
{% if article.owner == user %}
<a href="{% url 'myarts:article_update' article.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'myarts:article_delete' article.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ article.title }}</h1>
<p>
{{ article.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'myarts:all' %}">All articles</a>
</p>
{% endblock %}

ads/templates/ads/article_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
{% endblock %}

ads/templates/ads/article_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Articles</h1>
<p>
{% if article_list %}
<ul>
  {% for article in article_list %}
    <li>
        <a href="{% url 'myarts:article_detail'  article.id %}">{{ article.title }}</a>
        {% if article.owner == user %}
        (<a href="{% url 'myarts:article_update' article.id %}">Edit</a> |
        <a href="{% url 'myarts:article_delete' article.id %}">Delete</a>)
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no articles in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'myarts:article_create' %}">Add an Article</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'myarts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'myarts:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}